### ISSUE TITLE
Fedora 30: Recent Fedora updates breaks resolution

### ISSUE THREAD

**Issue by t3kg33k** [displaylink-rpm/displaylink-rpm#100]
I believe there were some Mesa drivers that were updated today that broke the resolution. Yesterday, I was able to use 1366x768. I completed Fedora updates today and the monitor was no longer detected. I reinstalled fedora-30-displaylink-1.6.2-1.x86_64.rpm however I'm only able to view at resolution of 1024x768 and below.

**Comment by t3kg33k** [comment]
I found that disabling Wayland fixed the issue.

**Comment by ssaavedra** [comment]
I didn't think Wayland was supported at all, but this kind of issue is probably not related to the packaging and should be directed to the displaylink forum.
