### ISSUE TITLE
RHEL8/CentOS 8 support

### ISSUE THREAD

**Issue by JonasKs** [displaylink-rpm/displaylink-rpm#101]
Any plans on supporting RHEL8, or does the #13 work arounds work in RHEL8 maybe?

EDIT: Tried to install just to check on my lab:
```bash
➜  ~ systemctl status displaylink.service
● displaylink.service - DisplayLink Manager Service
   Loaded: loaded (/usr/lib/systemd/system/displaylink.service; static; vendor preset: disabled)
   Active: active (running) since Tue 2019-08-13 16:10:09 CEST; 1min 7s ago
  Process: 4879 ExecStartPre=/sbin/modprobe evdi (code=exited, status=0/SUCCESS)
 Main PID: 4881 (DisplayLinkMana)
    Tasks: 11 (limit: 26213)
   Memory: 5.1M
   CGroup: /system.slice/displaylink.service
           └─4881 /usr/libexec/displaylink/DisplayLinkManager

```
Unfortunately, my displaylink adapter does not work.

**Comment by ssaavedra** [comment]
Disclaimer: no "support" is given, nor should be expected. This is just a community effort that tries to package the DisplayLink driver in a way more amenable to rpm-based systems.

I am completely open to accepting patches to CentOS 8 (or even CentOS 7, which is a long-standing open issue too), if you have the time to debug what's happening (in terms of needed dependencies, perhaps), and I'm sure someone could review the PR, if you can come up with one.

However, me in particular, I am no longer using DisplayLink-enabled hardware (nor I'm using a CentOS system) to have an incentive to do this research by myself, but I could review changes authored by others.

I'm leaving this open in case you have the time and wants to communicate further :-)

**Comment by JonasKs** [comment]
No worries mate, makes perfect sense. It’s not super critical for me, but if I go back to a DisplayLink adapter I’ll debug more and re open.
