### ISSUE TITLE
Fedora 31 build ? 

### ISSUE THREAD

**Issue by rprihoda** [displaylink-rpm/displaylink-rpm#106]
I know it just came out and all, but what are the chances to get a Fedora 31 build up in the releases?

**Comment by fran-pastor** [comment]
+1

**Comment by sciancio** [comment]
+1

**Comment by trevh86** [comment]
+1

**Comment by ssaavedra** [comment]
I've just merged PR #107 getting that, as well as #111 with the latest version. I'll be cutting a new release in order to have everything built by Travis in a few minutes :-)
