### ISSUE TITLE
Fedora 31 - Single monitor stopped working.

### ISSUE THREAD

**Issue by egyas** [displaylink-rpm/displaylink-rpm#120]
I previously had the drivers from this repo working.  And oh, the worked well.  I have a HP Envy x360 (Bang & Olufsen, Family: 103C_5335KV HP Envy) use a dock/port replicator (that had DisplayLink chips in it) to get additional USB, network, and display ports.  You can see from the picture below that at one point, I had all three external monitors working.

The current layout is...
Left monitor (DVI-I-3-3): Connected via DisplayPort cable to dock.  1920x1080
Top monitor (DVI-I-2-2): Connected via HDMI cable to dock.  1920x1080.
Right monitor (DVI-I-a-a): Connected via DisplayLink USB adapter to USB port on the dock.  1920x1080.

The top monitor is no longer displaying anything.  As you can see form the XrandR & ArandR pics below, both are recognized.  More over, the system seems to think that the top monitor is working, because when I move my mouse up there it disappears, and if I move it over to the left monitor, it comes out where it should be.  Apps that were set to spawn on that display previously still go there when I launch them, and I have to blindly grab for them and drag them down.

So the system sees that top monitor, and seems to think it's using it, AND I see the monitor's backlight so it''s not "dead", but there is no image displayed there.

Odder yet, if I disconnect that monitor, the left monitor (DVI-I-3-3) will not display.  I have to plug the other one back in in order to get it to come back to life.

Like I said, it WAS working fine, and I did NOT upgrade the kernel at all.  I rebooted one day and it just stopped working.

Unfortunately I can't swap cables or ports since one is DP/DVI only, and the other is HDMI only.  I reinstalled the drivers, but that had no impact.

Anyone have any ideas on how to restore full functionality?  Thanks!

Dock: MediaGear Dual Display USB-C docking station
https://www.mediagearpro.com/store/p33/DK0004.html
![Layout](https://user-images.githubusercontent.com/36460246/75489156-57f6e500-5977-11ea-956e-addb2dc9d338.jpg)
![XrandR](https://user-images.githubusercontent.com/36460246/75490237-6ba34b00-5979-11ea-943b-007b1a808851.png)
![ArandR](https://user-images.githubusercontent.com/36460246/75490246-6fcf6880-5979-11ea-800e-033ef4b4aa41.png)

**Comment by gdlin** [comment]
@egyas if your top monitor has 2 hdmi ports, try connecting one of those to the hdmi of the computer and check if it works. This is NOT to get the hdmi output. It happened to me (IDK why honestly) with one screen. Like it was a ground problem or something, but the behavior was similar to what you are describing. I ended up connecting and HDMI cable between two monitors. It makes NO SENSE, but it's working since!

**Comment by elguero** [comment]
@egyas Were you able to get this resolved?

**Comment by egyas** [comment]
I was not.  The monitor works fine on its own. But it still does not work in this configuration anymore.

**Comment by elguero** [comment]
@egyas Have you been able to try the latest release out?

**Comment by egyas** [comment]
@elguero I just tried it today.  Same as before.  :(

**Comment by egyas** [comment]
@elguero So this was odd.  I had some issues with an unrelated software package (my company's VPN client), which forced me to reboot over the weekend.  When the laptop came back up, all of my display settings for the DisplayLink were gone, monitor's weren't recognized, etc.  I reinstalled the drivers, and this time it all worked.  So I'm back to all 4 screen working.  Ha!

**Comment by egyas** [comment]
Thank you for the update!  :)  Closing issue.

**Comment by elguero** [comment]
@egyas Thanks for the update.  Glad that all is working now.
