### ISSUE TITLE
On a fresh install dependencies aren't set accordingly

### ISSUE THREAD

**Issue by gbraad** [displaylink-rpm/displaylink-rpm#139]
When install the displaylink=rpm with yum it will not satisfy development packages needs"

```
usr/sbin/dkms: line 98: make: command not found
```

**Comment by elguero** [comment]
@gbraad Can you post any logs? (`/var/log/displaylink/displaylink.log`)

Then try running `sudo dnf install make`.  Please report back.  We may need to make adjustments to .spec file to check that tools needed by dkms are installed.

**Comment by gbraad** [comment]
I already installed make, but using groupinstall "Development Tools".

Will check tomorrow if just 'make' satisfies

**Comment by elguero** [comment]
I can confirm that `make` needs to be specified as being required to install the rpm since dkms needs to use it to build the evdi module.

Thank you for your help.
