### ISSUE TITLE
Does displaylink-1.7.0-1.x86_64 work on CentOS 7?

### ISSUE THREAD

**Issue by rbarakjsonar** [displaylink-rpm/displaylink-rpm#140]
Hi Michael,
On which CentOS versions did displaylink-1.7.0-1.x86_64 run?
When I tried to install it on CentOS 7, I got the following unresolved dependencies:

> --> Processing Dependency: kernel-mt-devel >= 4.15 for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: dkms for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: libstdc++.so.6(CXXABI_1.3.8)(64bit) for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: libstdc++.so.6(CXXABI_1.3.9)(64bit) for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.20)(64bit) for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.21)(64bit) for package: displaylink-1.7.0-1.x86_64
> --> Running transaction check
> ---> Package displaylink.x86_64 0:1.7.0-1 will be installed
> --> Processing Dependency: kernel-mt >= 4.15 for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: kernel-mt-devel >= 4.15 for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: libstdc++.so.6(CXXABI_1.3.8)(64bit) for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: libstdc++.so.6(CXXABI_1.3.9)(64bit) for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.20)(64bit) for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.21)(64bit) for package: displaylink-1.7.0-1.x86_64
> ---> Package dkms.noarch 0:2.8.1-4.20200214git5ca628c.el7 will be installed
> --> Processing Dependency: elfutils-libelf-devel for package: dkms-2.8.1-4.20200214git5ca628c.el7.noarch
> --> Running transaction check
> ---> Package displaylink.x86_64 0:1.7.0-1 will be installed
> --> Processing Dependency: kernel-mt >= 4.15 for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: kernel-mt-devel >= 4.15 for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: libstdc++.so.6(CXXABI_1.3.8)(64bit) for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: libstdc++.so.6(CXXABI_1.3.9)(64bit) for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.20)(64bit) for package: displaylink-1.7.0-1.x86_64
> --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.21)(64bit) for package: displaylink-1.7.0-1.x86_64
> ---> Package elfutils-libelf-devel.x86_64 0:0.176-4.el7 will be installed
> --> Finished Dependency Resolution
> Error: Package: displaylink-1.7.0-1.x86_64 (/centos-7-displaylink-1.7.0-1.x86_64)
>            Requires: libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
> Error: Package: displaylink-1.7.0-1.x86_64 (/centos-7-displaylink-1.7.0-1.x86_64)
>            Requires: libstdc++.so.6(GLIBCXX_3.4.20)(64bit)
> Error: Package: displaylink-1.7.0-1.x86_64 (/centos-7-displaylink-1.7.0-1.x86_64)
>            Requires: kernel-mt-devel >= 4.15
> Error: Package: displaylink-1.7.0-1.x86_64 (/centos-7-displaylink-1.7.0-1.x86_64)
>            Requires: libstdc++.so.6(CXXABI_1.3.8)(64bit)
> Error: Package: displaylink-1.7.0-1.x86_64 (/centos-7-displaylink-1.7.0-1.x86_64)
>            Requires: libstdc++.so.6(CXXABI_1.3.9)(64bit)
> Error: Package: displaylink-1.7.0-1.x86_64 (/centos-7-displaylink-1.7.0-1.x86_64)
>            Requires: kernel-mt >= 4.15
>  You could try using --skip-broken to work around the problem
>  You could try running: rpm -Va --nofiles --nodigest

As my CentOS kernel is 3.10.0-1127.10.1.el7.x86_64, I'm wondering on which CentOS version you developed/tested `https://github.com/displaylink-rpm/displaylink-rpm/releases/download/v5.3.1/centos-7-displaylink-1.7.0-1.x86_64.rpm`

Thanks,
Ron.

**Comment by elguero** [comment]
@rbarakjsonar I think the question was directed at me. I have not tested this on CentOS 7.  It is part of the CI build before my time.  If the latest version no longer works with CentOS 7 because of the new minimum kernel version supported, then we may need to remove the RPM from being built for it.

It would be good to hear from others as to whether they are using this RPM and what they did to get it to work.

There are open issues around CentOS 7 on prior versions such as #13 and #85.  Not sure what the status was on CentOS 7 support.
