### ISSUE TITLE
Fedora 33 Kernel 5.11.15-200.fc33.x86_64 external monitors not working

### ISSUE THREAD

**Issue by sebastiano1972** [displaylink-rpm/displaylink-rpm#165]
Hi,

Thank you for your hard work. 

I just downloaded and installed the latest rpm but after installing it and rebooting the laptop with the docking station attached, I am getting the following error and the attached external monitors remain blank.

Maybe I've done something wrong but I thought it would be useful to report the problem.

Many thanks.

Sebastiano

My system is:

DisplayLink 5.4* and *evdi v1.9.1* on Fedora 33 Kernel 5.11.15-200.fc33.x86_64 on Lenovo L14 Ryzen pro 4750U attached to Lenovo docking station USB C type 40AF with Display Link Chipset.

The journalctl output is:

Apr 23 19:22:48 Obsidian systemd[1]: Stopped DisplayLink Manager Service.
Apr 23 19:22:48 Obsidian audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=>
Apr 23 19:22:48 Obsidian audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit>
Apr 23 19:22:48 Obsidian systemd[1]: displaylink.service: Scheduled restart job, restart counter is at 5.
Apr 23 19:22:46 Obsidian audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=>
Apr 23 19:22:46 Obsidian systemd[1]: NetworkManager-dispatcher.service: Succeeded.
Apr 23 19:22:43 Obsidian systemd[1]: Failed to start DisplayLink Manager Service.
Apr 23 19:22:43 Obsidian systemd[1]: displaylink.service: Failed with result 'exit-code'.
Apr 23 19:22:43 Obsidian systemd[1]: displaylink.service: Control process exited, code=exited, status=1/FAILURE
Apr 23 19:22:43 Obsidian audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit>
Apr 23 19:22:43 Obsidian kernel: Loading of unsigned module is rejected
Apr 23 19:22:43 Obsidian modprobe[2566]: modprobe: ERROR: could not insert 'evdi': Key was rejected by service
Apr 23 19:22:43 Obsidian systemd[1]: Starting DisplayLink Manager Service...

[displaylink.log](https://github.com/displaylink-rpm/displaylink-rpm/files/6367479/displaylink.log)

**Comment by elguero** [comment]
Do you have secure boot enabled?

If you do, check out the README: https://github.com/displaylink-rpm/displaylink-rpm#secure-boot-on-fedora

**Comment by sebastiano1972** [comment]
My bad, sorry. I just disabled the secure boot but still no joy.
If I connect and disconnect the docking station only the audio and the nic seems to be recognised correctly.

Below the journalctl when I connect the docking station to the laptop.


Apr 23 20:09:13 Obsidian mtp-probe[2652]: bus: 4, device: 13 was not an MTP device
Apr 23 20:09:13 Obsidian mtp-probe[2652]: checking bus 4, device 13: "/sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb4>
Apr 23 20:09:13 Obsidian mtp-probe[2649]: bus: 4, device: 13 was not an MTP device
Apr 23 20:09:13 Obsidian mtp-probe[2649]: checking bus 4, device 13: "/sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb4>
Apr 23 20:09:13 Obsidian kernel: usb 4-1.4.2.1: Manufacturer: Cypress Semiconductor
Apr 23 20:09:13 Obsidian kernel: usb 4-1.4.2.1: Product: USB-Serial Bridge
Apr 23 20:09:13 Obsidian kernel: usb 4-1.4.2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Apr 23 20:09:13 Obsidian kernel: usb 4-1.4.2.1: New USB device found, idVendor=04b4, idProduct=5218, bcdDevice= 0.00
Apr 23 20:09:12 Obsidian kernel: usb 4-1.4.2.1: new full-speed USB device number 13 using xhci_hcd
Apr 23 20:09:12 Obsidian plasmashell[1797]: org.kde.plasma.pulseaudio: No object for name "alsa_input.usb-DisplayLink_ThinkP>
Apr 23 20:09:12 Obsidian rtkit-daemon[987]: Supervising 5 threads of 1 processes of 1 users.
Apr 23 20:09:12 Obsidian rtkit-daemon[987]: Successfully made thread 2644 of process 1835 (/usr/bin/pulseaudio) owned by '10>
Apr 23 20:09:12 Obsidian upowerd[999]: treating change event as add on /sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb>
Apr 23 20:09:12 Obsidian rtkit-daemon[987]: Supervising 4 threads of 1 processes of 1 users.
Apr 23 20:09:12 Obsidian kernel: hub 4-1.4.2:1.0: 4 ports detected
Apr 23 20:09:12 Obsidian kernel: hub 4-1.4.2:1.0: USB hub found
Apr 23 20:09:12 Obsidian rtkit-daemon[987]: Supervising 4 threads of 1 processes of 1 users.
Apr 23 20:09:12 Obsidian rtkit-daemon[987]: Successfully made thread 2642 of process 1835 (/usr/bin/pulseaudio) owned by '10>
Apr 23 20:09:12 Obsidian kernel: usb 4-1.4.2: Product: USB 2.0 Hub [MTT]
Apr 23 20:09:12 Obsidian kernel: usb 4-1.4.2: New USB device strings: Mfr=0, Product=1, SerialNumber=0
Apr 23 20:09:12 Obsidian kernel: usb 4-1.4.2: New USB device found, idVendor=1a40, idProduct=0101, bcdDevice= 1.00
Apr 23 20:09:12 Obsidian rtkit-daemon[987]: Supervising 3 threads of 1 processes of 1 users.
Apr 23 20:09:12 Obsidian kernel: usb 4-1.4.2: new high-speed USB device number 12 using xhci_hcd
Apr 23 20:09:11 Obsidian upowerd[999]: treating change event as add on /sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb>
Apr 23 20:09:11 Obsidian upowerd[999]: treating change event as add on /sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb>
Apr 23 20:09:11 Obsidian plasmashell[1797]: UdevQt: unhandled device action "move"
Apr 23 20:09:11 Obsidian kded5[1709]: plasma-nm: Unhandled active connection state change:  1
Apr 23 20:09:11 Obsidian kded5[1709]: plasma-nm: Unhandled active connection state change:  1
Apr 23 20:09:11 Obsidian avahi-daemon[964]: Registering new address record for fe80::fba6:132b:2ac7:81a2 on enp6s0f4u1u3c2.*.
Apr 23 20:09:11 Obsidian avahi-daemon[964]: New relevant interface enp6s0f4u1u3c2.IPv6 for mDNS.
Apr 23 20:09:11 Obsidian avahi-daemon[964]: Joining mDNS multicast group on interface enp6s0f4u1u3c2.IPv6 with address fe80:>
Apr 23 20:09:11 Obsidian NetworkManager[1110]: <info>  [1619204951.8625] dhcp4 (enp6s0f4u1u3c2): activation: beginning trans>
Apr 23 20:09:11 Obsidian NetworkManager[1110]: <info>  [1619204951.8621] device (enp6s0f4u1u3c2): state change: config -> ip>
Apr 23 20:09:11 Obsidian audit[968]: NETFILTER_CFG table=?:0;?:0 family=0 entries=11 op=nft_register_gen pid=968 subj=system>
Apr 23 20:09:11 Obsidian audit[968]: NETFILTER_CFG table=firewalld:3;filter_FORWARD_OUT_ZONES:102 family=1 entries=416 op=nf>
Apr 23 20:09:11 Obsidian audit[968]: NETFILTER_CFG table=firewalld:3;filter_FORWARD_IN_ZONES:100 family=1 entries=415 op=nft>
Apr 23 20:09:11 Obsidian audit[968]: NETFILTER_CFG table=firewalld:3;filter_INPUT_ZONES:91 family=1 entries=414 op=nft_regis>
Apr 23 20:09:11 Obsidian audit[968]: NETFILTER_CFG table=firewalld:5;nat_POSTROUTING_ZONES:29 family=10 entries=108 op=nft_r>
Apr 23 20:09:11 Obsidian audit[968]: NETFILTER_CFG table=firewalld:4;nat_POSTROUTING_ZONES:29 family=2 entries=108 op=nft_re>
Apr 23 20:09:11 Obsidian audit[968]: NETFILTER_CFG table=firewalld:5;nat_PREROUTING_ZONES:26 family=10 entries=107 op=nft_re>
Apr 23 20:09:11 Obsidian audit[968]: NETFILTER_CFG table=firewalld:4;nat_PREROUTING_ZONES:26 family=2 entries=107 op=nft_reg>
Apr 23 20:09:11 Obsidian audit[968]: NETFILTER_CFG table=firewalld:3;mangle_PREROUTING_ZONES:82 family=1 entries=413 op=nft_>
Apr 23 20:09:11 Obsidian audit[968]: NETFILTER_CFG table=firewalld:3;raw_PREROUTING_ZONES:79 family=1 entries=412 op=nft_reg>
Apr 23 20:09:11 Obsidian baloo_file[1804]: UdevQt: unhandled device action "move"
Apr 23 20:09:11 Obsidian org_kde_powerdevil[1866]: UdevQt: unhandled device action "move"
Apr 23 20:09:11 Obsidian upowerd[999]: treating change event as add on /sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb>
Apr 23 20:09:11 Obsidian NetworkManager[1110]: <info>  [1619204951.8470] device (enp6s0f4u1u3c2): state change: prepare -> c>
Apr 23 20:09:11 Obsidian NetworkManager[1110]: <info>  [1619204951.8466] device (enp6s0f4u1u3c2): state change: disconnected>
Apr 23 20:09:11 Obsidian systemd-udevd[2620]: Using default interface naming scheme 'v245'.
Apr 23 20:09:11 Obsidian NetworkManager[1110]: <info>  [1619204951.8461] device (enp6s0f4u1u3c2): Activation: starting conne>
Apr 23 20:09:11 Obsidian NetworkManager[1110]: <info>  [1619204951.8454] policy: auto-activating connection 'Wired connectio>
Apr 23 20:09:11 Obsidian NetworkManager[1110]: <info>  [1619204951.8435] device (enp6s0f4u1u3c2): state change: unavailable >
Apr 23 20:09:11 Obsidian mtp-probe[2625]: bus: 5, device: 8 was not an MTP device
Apr 23 20:09:11 Obsidian mtp-probe[2625]: checking bus 5, device 8: "/sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb5/>
Apr 23 20:09:11 Obsidian NetworkManager[1110]: <info>  [1619204951.8348] settings: (enp6s0f4u1u3c2): created default wired c>
Apr 23 20:09:11 Obsidian NetworkManager[1110]: <info>  [1619204951.8319] device (enp6s0f4u1u3c2): carrier: link connected
Apr 23 20:09:11 Obsidian NetworkManager[1110]: <info>  [1619204951.8305] device (enp6s0f4u1u3c2): state change: unmanaged ->>
Apr 23 20:09:11 Obsidian NetworkManager[1110]: <info>  [1619204951.8142] device (eth0): interface index 9 renamed iface from>
Apr 23 20:09:11 Obsidian kernel: cdc_ether 5-1.3:2.0 enp6s0f4u1u3c2: renamed from eth0
Apr 23 20:09:11 Obsidian mtp-probe[2623]: bus: 5, device: 7 was not an MTP device
Apr 23 20:09:11 Obsidian mtp-probe[2623]: checking bus 5, device 7: "/sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb5/>
Apr 23 20:09:11 Obsidian systemd-udevd[2613]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not wri>
Apr 23 20:09:11 Obsidian systemd-udevd[2613]: Using default interface naming scheme 'v245'.
Apr 23 20:09:11 Obsidian systemd[1570]: Reached target Sound Card.
Apr 23 20:09:11 Obsidian mtp-probe[2614]: bus: 5, device: 7 was not an MTP device
Apr 23 20:09:11 Obsidian mtp-probe[2615]: bus: 5, device: 8 was not an MTP device
Apr 23 20:09:11 Obsidian mtp-probe[2614]: checking bus 5, device 7: "/sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb5/>
Apr 23 20:09:11 Obsidian mtp-probe[2615]: checking bus 5, device 8: "/sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb5/>
Apr 23 20:09:11 Obsidian kernel: hub 5-1.4:1.0: 4 ports detected
Apr 23 20:09:11 Obsidian kernel: hub 5-1.4:1.0: USB hub found
Apr 23 20:09:11 Obsidian kernel: usb 5-1.4: Manufacturer: VIA Labs, Inc.         
Apr 23 20:09:11 Obsidian kernel: usb 5-1.4: Product: USB3.1 Hub             
Apr 23 20:09:11 Obsidian kernel: usb 5-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Apr 23 20:09:11 Obsidian kernel: usb 5-1.4: New USB device found, idVendor=17ef, idProduct=a357, bcdDevice=55.44
Apr 23 20:09:11 Obsidian kernel: usb 5-1.4: new SuperSpeed Gen 1 USB device number 9 using xhci_hcd
Apr 23 20:09:11 Obsidian NetworkManager[1110]: <info>  [1619204951.6323] manager: (eth0): new Ethernet device (/org/freedesk>
Apr 23 20:09:11 Obsidian kernel: cdc_ether 5-1.3:2.0 eth0: register 'cdc_ether' at usb-0000:06:00.4-1.3, CDC Ethernet Device>
Apr 23 20:09:11 Obsidian kernel: usb 5-1.3: SerialNumber: 3010D2AAD
Apr 23 20:09:11 Obsidian kernel: usb 5-1.3: Manufacturer: Lenovo
Apr 23 20:09:11 Obsidian kernel: usb 5-1.3: Product: ThinkPad Lan
Apr 23 20:09:11 Obsidian kernel: usb 5-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=6
Apr 23 20:09:11 Obsidian kernel: usb 5-1.3: New USB device found, idVendor=17ef, idProduct=a359, bcdDevice=31.03
Apr 23 20:09:11 Obsidian kernel: usb 5-1.3: new SuperSpeed Gen 1 USB device number 8 using xhci_hcd
Apr 23 20:09:11 Obsidian kernel: hub 4-1.4:1.0: 4 ports detected
Apr 23 20:09:11 Obsidian kernel: hub 4-1.4:1.0: USB hub found
Apr 23 20:09:11 Obsidian kernel: usb 4-1.4: Manufacturer: VIA Labs, Inc.         
Apr 23 20:09:11 Obsidian kernel: usb 4-1.4: Product: USB2.0 Hub             
Apr 23 20:09:11 Obsidian kernel: usb 4-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Apr 23 20:09:11 Obsidian kernel: usb 4-1.4: New USB device found, idVendor=17ef, idProduct=1029, bcdDevice=55.44
Apr 23 20:09:11 Obsidian kernel: usb 4-1.4: new high-speed USB device number 11 using xhci_hcd
Apr 23 20:09:11 Obsidian kernel: usb 5-1.2: [7] FU [Lenovo USB Audio Playback Volume] ch = 6, val = -10752/0/16
Apr 23 20:09:11 Obsidian kernel: usb 5-1.2: Warning! Unlikely big volume range (=672), cval->res is probably wrong.
Apr 23 20:09:11 Obsidian kernel: usb 5-1.2: [4] FU [Mic Capture Volume] ch = 2, val = -4592/7680/16
Apr 23 20:09:11 Obsidian kernel: usb 5-1.2: Warning! Unlikely big volume range (=767), cval->res is probably wrong.
Apr 23 20:09:11 Obsidian kernel: usb 5-1.2: SerialNumber: 11799092
Apr 23 20:09:11 Obsidian kernel: usb 5-1.2: Manufacturer: DisplayLink
Apr 23 20:09:11 Obsidian kernel: usb 5-1.2: Product: ThinkPad Hybrid USB-C with USB-A Dock
Apr 23 20:09:11 Obsidian kernel: usb 5-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Apr 23 20:09:11 Obsidian kernel: usb 5-1.2: New USB device found, idVendor=17e9, idProduct=6015, bcdDevice=31.04
Apr 23 20:09:11 Obsidian kernel: usb 5-1.2: new SuperSpeed Gen 1 USB device number 7 using xhci_hcd
Apr 23 20:09:10 Obsidian kernel: usb 4-1.3: new high-speed USB device number 10 using xhci_hcd
Apr 23 20:09:09 Obsidian upowerd[999]: treating change event as add on /sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb>
Apr 23 20:09:09 Obsidian upowerd[999]: treating change event as add on /sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb>
Apr 23 20:09:09 Obsidian kernel: hub 5-1:1.0: 4 ports detected
Apr 23 20:09:09 Obsidian kernel: hub 5-1:1.0: USB hub found
Apr 23 20:09:09 Obsidian kernel: usb 5-1: Manufacturer: VIA Labs, Inc.         
Apr 23 20:09:09 Obsidian kernel: usb 5-1: Product: USB3.1 Hub             
Apr 23 20:09:09 Obsidian kernel: usb 5-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Apr 23 20:09:09 Obsidian kernel: usb 5-1: New USB device found, idVendor=17ef, idProduct=a356, bcdDevice=55.43
Apr 23 20:09:09 Obsidian kernel: usb 5-1: new SuperSpeed Gen 1 USB device number 6 using xhci_hcd
Apr 23 20:09:09 Obsidian kernel: hub 4-1:1.0: 4 ports detected
Apr 23 20:09:09 Obsidian kernel: hub 4-1:1.0: USB hub found
Apr 23 20:09:09 Obsidian kernel: usb 4-1: Manufacturer: VIA Labs, Inc.         
Apr 23 20:09:09 Obsidian kernel: usb 4-1: Product: USB2.0 Hub             
Apr 23 20:09:09 Obsidian kernel: usb 4-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Apr 23 20:09:09 Obsidian kernel: usb 4-1: New USB device found, idVendor=17ef, idProduct=1028, bcdDevice=55.43
Apr 23 20:09:09 Obsidian kernel: usb 4-1: new high-speed USB device number 9 using xhci_hcd

**Comment by sebastiano1972** [comment]
I re-enabled the secure-boot. I will try with the suggested procedure.

**Comment by sebastiano1972** [comment]
Ok, I removed the rpm and checked all the folders as suggested when I opened the issue. I re-enabled the secure boot, and I followed the instructions to sign the module. The good news is that then the external monitors now both work. The bad news are:

1) I can only use one external monitor (4K@60) and the laptop monitor or both the external monitors only (4K@60) but not the laptop monitor. maybe this is a hardware limit though.

2) when hooked to the docking startion the laptop becomes extremely laggy to the point it is almost un-usable (I cannot ytpe more than 1 char per 2 secs on the teminal, mouse movements are choppy and cannot wven browse the internet as it takes forever to open a page)

3) I can confirm th power usage of the laptop increases when it is attached to the docking station as per the attached
 powertop report. Disconnecting the laptop from the docking station solves the power consumption issue.

[Uploading report.txt…]()

**Comment by elguero** [comment]
@sebastiano1972 Perhaps you are having the same issue that was reported to DisplayLink on their repo: https://github.com/DisplayLink/evdi/issues/271

**Comment by sebastiano1972** [comment]
@elguero It seems a very similar issue indeed. Although only Wayland and X11 are mentioned and I use Kde instead (it should be Qt based?). But the symptoms are the same.

**Comment by elguero** [comment]
@sebastiano1972 I thought that I saw someone reporting issues with KDE towards the bottom in one of the comments.

**Comment by husmanahmed** [comment]
Not sure if this helps with the diagnostics for this issue. I have just installed: fedora-33-displaylink-1.9.1-1.x86_64.rpm
on my Thinkpad T460s, running Fedora 33. 

> uname -a
Linux thinkpad 5.11.14-200.fc33.x86_64

The monitor connected to the HDMI port of my dock works (even before installing the displaylink driver)
The monitor connected to the DVI port of the dock is not recognised.

I tried installing the RPM with the monitor connected. I tried a reboot (or two).
Is there anything else I can provide to help diagnose the issue?

**Comment by elguero** [comment]
FYI: https://github.com/DisplayLink/evdi/pull/282

**Comment by husmanahmed** [comment]
> FYI: [DisplayLink/evdi#282](https://github.com/DisplayLink/evdi/pull/282)

Thank you for replying. I'm not quite sure if this relates to me, I am on an intel i5 processor.

**Comment by derekmurawsky** [comment]
FYI - I followed these instructions and everything worked. I think I upgraded my system before installing this rpm, but didn't reboot so things were out of sync. I uninstalled the rpm, upgraded everything, rebooted, reinstalled the RPM, and everything worked perfectly. 
Thanks for this package!!!

**Comment by elguero** [comment]
A newer RPM has been released.  Can you provide some feedback on whether this solves your issue?  Thanks.

**Comment by elguero** [comment]
Closing for now.
