### ISSUE TITLE
Fedora 34 support

### ISSUE THREAD

**Issue by lweller** [displaylink-rpm/displaylink-rpm#168]
Fedora 34 has been release a few day's ago, so support for it would be appreciated.

**Comment by lweller** [comment]
I just saw that fedora 34 target has already been added and build is passing. So mainly only a new release is required for a fedora 34 rpm to be available.

**Comment by flyize** [comment]
Any idea when we will see a Fedora 34 build?

**Comment by elguero** [comment]
A new release has been tagged so that a F34 RPM will be available.
