### ISSUE TITLE
Night light feature not working

### ISSUE THREAD

**Issue by skewty** [displaylink-rpm/displaylink-rpm#169]
Apparently Night light feature is available in Windows.  See: https://support.displaylink.com/knowledgebase/articles/1886413
Is there any chance we can get it working in linux too?

  * Fedora 34 (fedora-34-displaylink-1.9.1-1.x86_64.rpm)
  * Kernel linux fedora 5.11.21-300.fc34.x86_64 #1 SMP Fri May 14 17:43:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by elguero** [comment]
Here is a discussion over at DisplayLink's repo:

https://github.com/DisplayLink/evdi/issues/44
