### ISSUE TITLE
extrem lag and slow overall performance

### ISSUE THREAD

**Issue by groovyman** [displaylink-rpm/displaylink-rpm#174]
I am trying to run a new notebook with usb3.2 gen2 with 10Gb/s with a capable docking station usiing a DL-6000 chip.
The dockingstation comes with 3 display connectors but onyl 2 are working now.

Thank you , i was able to install the displaylink-rpm under Fedora F34.

The lack is a desaster. The displaylink process eats up more than 100% CPU time and seems to be part of the very slow overall output. Before i was able to run the same notebook with W10 on an old docking station with max 5Gb/s and i had absolutly no problem with 2 4K monitors and no CPU eating process.

Hardware:
. Lenovo 16p with AMD CPU
-  Startech DK31C3HDPD and 3 attached 4K Monitors

Just let you know: 2*4K Monitor did work with an old Docking station using a USB3 connection on Windows10.

-----
It looks like to be a driver issue. The strange thing is, that the process DisplayLinkMana ... 
eats up 125% of cpu time. When you perform a strace on that process, you might 
figure out, that the system is waiting in a SELECT with no return. Anyway, xosview tells me
that most of the CPU time is consumed in user mode.

$ journalctl -k -f
gives you tons of messages like this:
Aug 10 14:55:27 foreman kernel: evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
Aug 10 14:55:28 foreman kernel: evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
Aug 10 14:55:28 foreman kernel: evdi evdi.1: cannot be used for peer-to-peer DMA as it is not a PCI device
Aug 10 14:55:28 foreman kernel: evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
Aug 10 14:55:28 foreman kernel: evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device

-----

turn out to be this problem: https://github.com/DisplayLink/evdi/issues/248

Switching to one external monitor does not change the situation at all. There is still the same lag, so i believe that the USB3 Gen2 with 10Gb/s should not be the bottleneck.

**Comment by groovyman** [comment]
I was able to install a W10 on my laptop and was surprised what could be, if ....
There was a little lag, and a low CPU consumption. Besides i was able to adress all 3 of my 4K Monitors without any problem.

Maybe there is something wrong in the way, how the code accesses the USB on the AMD-Driven notebook.

**Comment by groovyman** [comment]
Dear @elguero 

in oder to figure out, why the DisplayManager eats up the CPU time i ran a strace on that process, and was surprised, that this process stayed in the execution of a select call. This means, that all burned CPU time is wasted in the kernel!
Did somebody figured out, what the hell the driver is doing there?
If not, i could perform a trace in order to figures out, whats wrong!

**Comment by elguero** [comment]
@groovyman Can you try the latest release?  I am seeing a lot of reports over on the [Displaylink/evdi ](https://github.com/DisplayLink/evdi/issues) repo. Maybe you can help add some information over there if you are still seeing this issue.

**Comment by elguero** [comment]
There is a new RPM package out.  Can you give that a try and provide some feedback?  Thanks.

**Comment by elguero** [comment]
Closing for now.
