### ISSUE TITLE
Can´t install displaylink after clean Fedora install

### ISSUE THREAD

**Issue by brunnogama** [displaylink-rpm/displaylink-rpm#203]
Hi!

After make a clean install of Fedora and add the negativo17 multimedia repo, I can´t install displaylink again:

**# dnf install displaylink
Error:
 Problem: package displaylink-5.5.0-4.fc35.x86_64 requires evdi-kmod >= 1.10.1, but none of the providers can be installed
  - package kmod-evdi-1.11.0-1.20220428git39da217.fc35.x86_64 requires akmod-evdi=1.11.0-1.20220428git39da217.fc35, but none of the providers can be installed
  - conflicting requests
  - nothing provides evdi-kmod-common >= 1.11.0 needed for akmod-evdi-1.11.0-1.20220428git39da217.fc35.x86_64
  - nothing provides evdi-kmod-common=1.11.0 needed for dkms-evdi-1.11.0-1.20220428git39da217.fc35.noarch
(try adding '--skip-broken' to skip uninstallable packages)**

Fedora 35
Kernel:
Linux moody-pc 5.17.4-200.fc35.x86_64 #1 SMP PREEMPT Wed Apr 20 15:37:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Let me know if I can provide more information.

**Comment by elguero** [comment]
You will need to reach out to the maintainer of that repo for support.

Thanks
