### ISSUE TITLE
RPM has unnecessary dependency on mutter

### ISSUE THREAD

**Issue by shoffmeister** [displaylink-rpm/displaylink-rpm#208]
The RPM has an unnecessary dependency on mutter, see https://github.com/displaylink-rpm/displaylink-rpm/blob/master/displaylink.spec#L59

There is nothing in the (current) DIsplayLink Ubuntu distribution that links to mutter components; there is only code which will special-case behaviour on "gnome-shell" to work around issues detect there.

On systems with KDE as the desktop environment, mutter is not present by default, so installing this RPM has the unpleasant side-effect of dragging in all the GNOME dependencies, for no good.

The declared dependency on mutter should therefore be removed.

**Comment by elguero** [comment]
Should be resolved with PR #222
