### ISSUE TITLE
Drop support for EOL distributions (e.g. Fedora 29)

### ISSUE THREAD

**Issue by shoffmeister** [displaylink-rpm/displaylink-rpm#210]
A number of distributions are EOL - e.g. much of Fedora, centos 8.

Stop building all EOL distributions, to simplify making progress on distributions that are not EOL, but healthy and alive. The oldest Linux distribution Synaptics themselves officially support is Ubuntu 20.04 (although the .run contains more), released 2020-04-23.

Case in point: [Fedora is planning to discard i686](https://fedoraproject.org/wiki/Changes/EncourageI686LeafRemoval) could be used as a motivation to not maintain i386 any more. 

With support for EOL distributions dropped, it becomes much more evident whether or not i386 should be dropped from this package, (and when)

**Comment by elguero** [comment]
I am all for simplifying.  Perhaps on the next round of releases, we can clean up the Fedora distros and CentOS 8.

**Comment by ParadoxGuitarist** [comment]
fwiw - I'm in favor of this. Fedora 38 is about to drop (currently in beta) , so the only supported versions are F36 for another month or so  and F37 and 38.
