### ISSUE TITLE
v5.6.0 Missing builds for Fedora 34, 35 and 36

### ISSUE THREAD

**Issue by ztoufie** [displaylink-rpm/displaylink-rpm#224]
The latest release v5.6.0 seems to be missing the builds for Fedora 34, 35 and 36. Also the build for Fedora 32 does not have a build for x86_64.

https://github.com/displaylink-rpm/displaylink-rpm/releases/tag/v5.6.0

**Comment by elguero** [comment]
@ztoufie Hi!  The release builds have not finished yet.  Please check back in a bit.

**Comment by ztoufie** [comment]
Will do, was just a bit over eager I guess :-)
