### ISSUE TITLE
DisplayLink Display doesn't refresh

### ISSUE THREAD

**Issue by mustacheride** [displaylink-rpm/displaylink-rpm#23]
I'm having an issue with the Disaplylink devices not updating the screen when things change. For instance, on the laptop screen I am typing this message now, however on the screens connected to the DisplayLink device, it shows the original image of the screen the last time I restarted the DisplaylinkManager. 

Device Info: 
Dell XPS 13 (9360)
Dell D3100 DisplayLink Docking Station
Fedora 25

`$ uname -r
4.10.6-200.fc25.x86_64`

`$ sudo modprobe evdi
$
`

`$ sudo systemctl status displaylink
● displaylink.service - DisplayLink Manager Service
   Loaded: loaded (/usr/lib/systemd/system/displaylink.service; static; vendor preset: disabled)
   Active: active (running) since Mon 2017-04-03 12:03:10 CDT; 6min ago
  Process: 12753 ExecStartPre=/sbin/modprobe evdi (code=exited, status=0/SUCCESS)
 Main PID: 12755 (DisplayLinkMana)
    Tasks: 43 (limit: 4915)
   CGroup: /system.slice/displaylink.service
           └─12755 /usr/libexec/displaylink/DisplayLinkManager

Apr 03 12:03:10  systemd[1]: Starting DisplayLink Manager Service...
Apr 03 12:03:10  systemd[1]: Started DisplayLink Manager Service.`

Everything was installed using the git source and running make inside the directory. I did have to perform the following steps before I could get the displaylink manager to run: 

`$ cd /usr/src/evdi-1.3.43/ && sudo make
`
`$ sudo insmod ./evdi.ko 
`
`$ sudo dkms install evdi/1.3.43
`

I can see the mouse movement on the DL attached screens, however the browser and workspace switcher does not update to match what is currently on the laptop screen. 

An example is attached showing the disparity between laptop screen and DL attached screen. 
![img_20170403_121305](https://cloud.githubusercontent.com/assets/15336577/24621806/77a7513a-1868-11e7-9f2e-862575c95e8e.jpg)

I'm guessing this is a conflict or something with the laptop's display driver and the DL driver? I'm not really sure whats going on here to cause this issue.

**Comment by reypm** [comment]
@ssaavedra @hadess this seems to be related with the issue I am having as in [here](https://github.com/displaylink-rpm/displaylink-rpm/issues/22#issuecomment-287349068), any advice or ideaS?

**Comment by Geodomus** [comment]
Also having this issue currently. May have something to do with a newer kernel version? (Blind guess).

**Comment by Geodomus** [comment]
just tested it with evdi 1.4. No changes, same bug

**Comment by ssaavedra** [comment]
Has this been addressed on the latest versions?

**Comment by choonming** [comment]
@ssaavedra I'm using the lastest RPM as of today. I can see my secondary display connected but the displays are not refreshing. I can see my mouse cursor hovering about not when I drag a window over there, nothing happens.

**Comment by ssaavedra** [comment]
Version 1.3.54 of the daemon has been released. The builds are now available thanks to #27 
Please, try again and report back.

**Comment by bowerth** [comment]
dark screen... only mouse cursor - depending on display setup, I get a wallpaper but not possible to move any window to DL screen (Lenovo LT1421, using evdi 1.4.1 and latest #27 )

**Comment by ssaavedra** [comment]
This seems to have been solved in the latest releases. Closing.
