### ISSUE TITLE
[D6000] monitors not recognized (hdmi or displayport)

### ISSUE THREAD

**Issue by emouty** [displaylink-rpm/displaylink-rpm#241]
## Context

  * Are you using the latest DisplayLink driver? yes : Displaylink 5.7.0
    
  * Are you using the latest EVDI module? 1.13.1
    
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?  yes
    
  * Is this issue related to evdi/kernel? not sure
    
  * Is this issue related to DisplayLinkManager? not sure
    
  * If you are having an issue upgrading, have you tried to do a clean install of the driver? yes
    

## Environment:

  * Fedora 38
  * Kernel version 6.2.14-300.fc38.x86_64 
  * `switcherooctl list`
	 ```
	Device: 0
	  Name:        Intel Corporation Alder Lake-P Integrated Graphics
	  Default:     yes
	  Environment: DRI_PRIME=pci-0000_00_02_0
	
	Device: 1
	  Name:        NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile]
	  Default:     no
	  Environment: __GLX_VENDOR_LIBRARY_NAME=nvidia __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only
	```

## Logs

  * `/var/log/displaylink/displaylink.log` : [displaylink.log](https://github.com/displaylink-rpm/displaylink-rpm/files/11409262/displaylink.log)

  * `/var/lib/dkms/evdi/kernel-[version]/log/make.log` : [make.log](https://github.com/displaylink-rpm/displaylink-rpm/files/11409261/make.log)
  * `dmesg` (after device has been connected)  : [dmesg.log](https://github.com/displaylink-rpm/displaylink-rpm/files/11409286/dmesg.log)

## Description

I have a D6000 and I just installed the displaylink driver the usb ports work fine but I cannot display anything from the hdmi or display port, my monitors aren't recognized. I have done a clean install but it's still not working. 

I'm not sure if I missed something or a tweak to do.

**Comment by pil-in-a** [comment]
I have the same problem on Lenovo X1 Carbon 5th gen.
Fedora: 37, kernel: 6.2.14-200.fc37.x86_64 (64-bit)
