### ISSUE TITLE
Package for Alma Linux 9?

### ISSUE THREAD

**Issue by tominglis** [displaylink-rpm/displaylink-rpm#246]
* Alma Linux
  * 9.2

I am planning to use Alma Linux 9.2 on my laptop, and am keen to use this driver. Are you able to produce a package for it?

You already cover CentOS, Fedora and Rocky. Given the popularity of Alma, I would have thought it would make sense too?

**Comment by mark-hyde** [comment]
I've been using the Rocky Linux package on my Alma Linux 8.8 laptop, so maybe you would be able to do the same using the rocky package for your Alma9.2 in the meanwhile?
