### ISSUE TITLE
Fedora 39 RPM?

### ISSUE THREAD

**Issue by webknjaz** [displaylink-rpm/displaylink-rpm#250]
F39 got released today: https://fedoramagazine.org/announcing-fedora-linux-39/. Is it possible to generate a new RPM for it?

**Comment by bennothommo** [comment]
The Fedora 38 driver still works - for me, at least.

**Comment by webknjaz** [comment]
I haven't tried reinstalling it upon upgrade. But the previously installed systemd unit crashes not finding a kernel module or something. Haven't looked into it more.

**Comment by bennothommo** [comment]
I am following the instructions for [signing the driver for secure boot](https://github.com/displaylink-rpm/displaylink-rpm#secure-boot-on-fedora), I did have a crash as well until I followed those steps.

**Comment by webknjaz** [comment]
I never had to go through the secure boot thing as I don't think I have it enabled.

**Comment by jtkellys** [comment]
I don't know if it's a crash, but only one of the display ports is working correctly. Any luck on figuring this out?
