### ISSUE TITLE
make devel does not build RPMs

### ISSUE THREAD

**Issue by Max-F-Helm** [displaylink-rpm/displaylink-rpm#254]
The make target `devel` just downloads the latest evdi-sources and puts them into a .tar.gz, but does not build the RPMs.
Using the `srpm` target uses the evdi-sources from the `Graphics_Software_for_Ubuntu_...` package, so seems to be no way to build the RPMs with the latest sources.

Build environment:
  - Fedora 39 (x64)
  - Kernel 6.6.2-201.fc39.x86_64

**Comment by elguero** [comment]
Hi @Max-F-Helm ,

You are correct.  Running `make devel` downloads the latest code from the evdi repo.  If you follow that with a `make` it will use that tarball that was created to make the SRPM and RPM files.
