### ISSUE TITLE
DISPLAYLINK FOR FEDORA39 

### ISSUE THREAD

**Issue by displaylinkhelp** [displaylink-rpm/displaylink-rpm#257]
cat /etc/os-release 
NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"
##########################################################################
$ sudo systemctl start displaylink-driver
Failed to start displaylink-driver.service: Unit displaylink-driver.service not found.
##########################################################################
Display link was installed 
sudo ./ci/fedora.sh 
Last metadata expiration check: 0:14:27 ago on Mon 29 Jan 2024 10:05:26 AM CST.
Package rpm-build-4.19.1-1.fc39.x86_64 is already installed.
Package make-1:4.4.1-2.fc39.x86_64 is already installed.
Package gcc-13.2.1-6.fc39.x86_64 is already installed.
Package gcc-c++-13.2.1-6.fc39.x86_64 is already installed.
Package libdrm-devel-2.4.120-1.fc39.x86_64 is already installed.
Package systemd-rpm-macros-254.8-2.fc39.noarch is already installed.
Package glibc-devel-2.38-14.fc39.x86_64 is already installed.
Package glibc-devel-2.38-14.fc39.i686 is already installed.
Package wget-1.21.3-7.fc39.x86_64 is already installed.
Package git-2.43.0-1.fc39.x86_64 is already installed.
Package dnf-plugins-core-4.4.4-1.fc39.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 0:14:28 ago on Mon 29 Jan 2024 10:05:26 AM CST.
Package gcc-c++-13.2.1-6.fc39.x86_64 is already installed.
Package libdrm-devel-2.4.120-1.fc39.x86_64 is already installed.
Package make-1:4.4.1-2.fc39.x86_64 is already installed.
Package systemd-rpm-macros-254.8-2.fc39.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
make: Nothing to be done for 'all'.

##########################################################################

**Comment by ssaavedra** [comment]
The CI script is not meant to install Displaylink on your system. CI means "continuous integration", that script is used to *build* the Fedora package.

If you want to just install the package, refer to the [Releases section](https://github.com/displaylink-rpm/displaylink-rpm/releases) in GitHub and install the built rpm using `dnf install <path-to-rpm>` or the graphical interface. If you don't see yours, click on "See all assets".

I'm going to close this issue, but if this is still not working, please feel free to reopen. Thanks!
