### ISSUE TITLE
Update package to incorporate displaylink 6.0 release

### ISSUE THREAD

**Issue by dan-lettusgrow** [displaylink-rpm/displaylink-rpm#265]
Displaylink have announced / released version 6.0 of their driver with the following changelog:

- DL-7xxx: Support for DP++ (HDMI) video
- DL-7xxx: Added Unigraf UCD-400/500 for DisplayPort compliance testing
- DL-6xxx series: incorrect image at 2560x1440@60 on some DisplayPort monitors
- Added preliminary support for kernel 6.9
- General stability updates and bug fixes

**Comment by GrzegorzBB** [comment]
Hi,
please take a look at #264
