### ISSUE TITLE
Relating to updates

### ISSUE THREAD

**Issue by mitmarcus** [displaylink-rpm/displaylink-rpm#277]
I have the github version installed *1.14.6-1, however dnf tries to update to 6.0.0
![image](https://github.com/user-attachments/assets/07995940-37bf-4bc7-a2d0-1eb5d935ef29)

Is it possible to update it on the rpm repo? or should I disable updates entirely to the package?

**Comment by elguero** [comment]
Hola @mitmarcus ,

Did you install from a `dnf` repository or did you install from the release here on GitHub?

**Comment by mitmarcus** [comment]
installed from here. The one from fedora @system seems outdated.

**Comment by mitmarcus** [comment]
Unfortunately, 6.1.0 no longer works. 
The one from GitHub is fine. The one from the official repo *that it always tries to update to* is not.

Am I the only one with this issue?

**Comment by elguero** [comment]
Hola @mitmarcus ,

What do you mean "official repo"?  This project doesn't have one.

It sounds like you may need to disable whatever repo you have enabled on your system.

Releases from this project are currently only available here on GitHub.

**Comment by mitmarcus** [comment]
![image](https://github.com/user-attachments/assets/7244a08d-70da-4d91-8c33-83424be48f2e)
![image](https://github.com/user-attachments/assets/ee0843f4-7288-4664-88f3-090040522957)

It seems to be in fedora multimedia? 
![image](https://github.com/user-attachments/assets/bd44beac-87d2-4f31-9430-824026b6b73f)

**Comment by elguero** [comment]
It looks like you have added a third party repo.  The repo is here: https://negativo17.org/

That has no relation to this project.  They might be repackaging our work from here which is causing the conflict on your system.

**Comment by mitmarcus** [comment]
Hola @elguero!

Thank you! I don't know how I missed this until now; I'm not even using that repo anymore.
