### ISSUE TITLE
Cron script to sign the driver at each boot

### ISSUE THREAD

**Issue by liloumuloup** [displaylink-rpm/displaylink-rpm#280]
* Are you using the latest DisplayLink driver? yes
    
  * Are you using the latest EVDI module? yes
    
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website? yes
    
  * Is this issue related to evdi/kernel? no
    
  * Is this issue related to DisplayLinkManager? no
    
  * If you are having an issue upgrading, have you tried to do a clean install of the driver?
    

  * Fedora
  * Version 40
  * Kernel version `(uname -a)` 6.10.12-200.fc40.x86_64

  * `/var/log/displaylink/displaylink.log`
  * `/var/lib/dkms/evdi/kernel-[version]/log/make.log`

Hello !
I'm sorry if it's not the good way to do it but i was not sure what was the best way to do it.
I wrote 2 scripts to make the signature of the driver being done at each computer boot, and send a notification to the user.
There are far from perfect, but I would like to share it to the community in case anyone needs it : 

* Crontab : 
```shell
@reboot sleep 60 && /home/<user>/git/scripts/certificate-base.sh
```

* Script executed by crontab `certificate-base.sh` :
```shell
#!/usr/bin/env bash
###
## command_success and command_fail function just displays notification using notify-send
## as critical so that I know if signature has ended successfully or not
###
BASE_PATH="/home/<username>/"
APP_NAME="Sign video driver"
ICON_PATH="${BASE_PATH}/Pictures/Logo-Signature.png"

# sudo -u <user> DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/<uid user>/bus notify-send 'Hello world!' 'This is an example notification.'

function command_success() {
  sudo -u <user> DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/<uid user>/bus notify-send --app-name="${APP_NAME}" --icon "${ICON_PATH}" --urgency normal "${1} ended successfully"
}

function command_fail() {
  sudo -u <user> DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/<uid user>/bus notify-send --app-name="${APP_NAME}" --icon "${ICON_PATH}" --urgency critical "${1} has failed"
}

${BASE_PATH}Documents/Configurations/driver-base/sign-driver-upgrade-kernel.sh && command_success "${APP_NAME}" || command_fail "${APP_NAME}"
```

* The `sign-driver-upgrade-kernel.sh` which makes the driver work, based on the Readme :
```shell
#!/usr/bin/env bash

BASE_PATH="/home/<user>/Documents/Configurations/driver-base/"

sudo modinfo -n evdi /lib/modules/$(uname -r)/extra/evdi.ko.xz

sudo unxz $(modinfo -n evdi)

sudo /usr/src/kernels/$(uname -r)/scripts/sign-file sha256 "${BASE_PATH}/MOK.priv" "${BASE_PATH}/MOK.der" /lib/modules/$(uname -r)/extra/evdi.ko

sudo xz -f /lib/modules/$(uname -r)/extra/evdi.ko
```

**Comment by elguero** [comment]
Hola @liloumuloup ,

Thank you for sharing.

It should not be necessary to sign the kernel module at every reboot.  Once the key that was generated by DKMS is enrolled in your system, DKMS will auto sign any modules built with it.  We are using DKMS in this installation package and it will auto sign the module when being installed or when new kernels are released which executes the module to be built against the new kernel.
