### ISSUE TITLE
Doesn't work on Fedora 41 kernels - 6.11.7-300 up

### ISSUE THREAD

**Issue by BnS2** [displaylink-rpm/displaylink-rpm#283]
Installed the latest displaylink-rpm. but it seems to work only in 6.11.6-200, but doesn't work (no connection) with the new kernels. Any solution on this? thanks

**Comment by ryenigma** [comment]
Same on 6.11.8-300.  Quick iterations on kernels is less than ideal I would imagine.

**Comment by BnS2** [comment]
Too bad, I only have integrated graphics. Intel® Iris® Plus Graphics (ICL GT1.5)

**Comment by BnS2** [comment]
Cloned and make, installed again fresh #259 (using the kernel 6.11.8-300.fc41.x86_64) made it work, maybe just a symlink issue for the kernel. thanks
