### ISSUE TITLE
F26 Dell XPS 13 square monitor resolutions

### ISSUE THREAD

**Issue by domyeung** [displaylink-rpm/displaylink-rpm#31]
Hi there,
Not entirely sure if this is something I should be raising here or with EVDI.
I have just upgraded from Fedora 24 -> 26 and have all monitors "working"/ displaying something.
However the builtin laptop monitor will not allow me to select any rectangular resolutions to make use of the whole real estate (16:9), so at the moment that is stuck on 4:3 resolution.
If I choose the top resolution of 3200x1800 I am unable to use all monitors (because the total resolution area is too large)

It would be great to continue using the 3 external monitors and to set the laptop to 1920x1080 (or something similar)

(I was able to use the full laptop resolution, and monitor setup back on Fedora 24 and kernel 4.7.9-200)

System Information
	Manufacturer: Dell Inc.
	Product Name: XPS 13 9343
	Version: Not Specified
	Serial Number: 683TL32
	UUID: 4C4C4544-0038-3310-8054-B6C04F4C3332
	Wake-up Type: Power Switch
	SKU Number: 0665
	Family: Not Specified

Using a Dell D3100
Kernel: 4.11.11-300.fc26.x86_64
Package: displaylink-1.4.1-4.x86_64
SELinux: enforcing

I have also attached my xrandr output
[xrandr-output.txt](https://github.com/displaylink-rpm/displaylink-rpm/files/1190729/xrandr-output.txt)

Thanks

**Comment by ssaavedra** [comment]
I think this should be raised at evdi or at the DisplayLink forums; this repo just takes care of the packaging, and the packaging is identical in both Fedora versions.

From your description, I don't think your issue is related to the packaging, but if you think I'm wrong, please reopen the issue.
