### ISSUE TITLE
Fedora 27 (beta) 4.13.5-300.fc27.x86_64

### ISSUE THREAD

**Issue by bowerth** [displaylink-rpm/displaylink-rpm#42]
Hello, better early than never - 
anyone tried Fedora 27 beta? just upgraded to kernel 4.13.5-300.fc27.x86_64 and experience the usual big black...

**Comment by bowerth** [comment]
update to evdi 1.5.0 and installing displaylink-1.5.0-1.x86_64.rpm solved the issue

**Comment by Blackjack92** [comment]
@bowerth  how have you installed the evdi 1.5.0 because I get the following error, when I try to `make` evdi 1.5.0:

> /lib/modules/4.13.9-300.fc27.x86_64/build: No such file or directory.  Stop.
