### ISSUE TITLE
Asus Dock Outputs Mirrored Only 

### ISSUE THREAD

**Issue by dalangston** [displaylink-rpm/displaylink-rpm#44]
I've been using an Asus USB 3.0 HZ-1 Docking Station for some time.  The dock has DVI, VGA, and HDMI outputs, of which you can use two at a time.  I have the dock connected to two external monitors on the VGA and DVI outputs.  

Currently, the external displays show the same image.  Previously, I was able to use them as independent displays, in the same configuration.

I'm not sure when this stopped working, as I've had to travel for work, and I've been through several kernel upgrades since.  The oldest kernel currently installed is `4.13.4-200.fc26.x86_64`, which exhibited the same behaviour.

Xrandr shows only one `modesetting` interface; it used to see two.

```
$ xrandr --listproviders 
Providers: number : 3
Provider 0: id: 0x8f cap: 0xb, Source Output, Sink Output, Sink Offload crtcs: 3 outputs: 5 associated providers: 2 name:Intel
Provider 1: id: 0x17e cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 1 name:modesetting
Provider 2: id: 0x62 cap: 0x7, Source Output, Sink Output, Source Offload crtcs: 2 outputs: 1 associated providers: 1 name:nouveau
```

I used to get two outputs starting with `DVI-I-`; now there is only  one.

```
$ xrandr | awk '/connect/'
LVDS1 connected primary 1366x768+0+282 (normal left inverted right x axis y axis) 340mm x 190mm
DP1 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
VGA1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
DVI-I-2-1 connected 1680x1050+1366+0 (normal left inverted right x axis y axis) 474mm x 296mm
VGA-1-2 connected (normal left inverted right x axis y axis)
```

displaylink.service starts up on boot

```
$ systemctl status displaylink
● displaylink.service - DisplayLink Manager Service
   Loaded: loaded (/usr/lib/systemd/system/displaylink.service; static; vendor preset: disabled)
   Active: active (running) since Sun 2017-10-29 07:27:33 EDT; 4min 28s ago
  Process: 1338 ExecStartPre=/sbin/modprobe evdi (code=exited, status=0/SUCCESS)
 Main PID: 1345 (DisplayLinkMana)
    Tasks: 26 (limit: 4915)
   CGroup: /system.slice/displaylink.service
           └─1345 /usr/libexec/displaylink/DisplayLinkManager

```

I don't see any `displaylink` or `evdi` errors in `journalctl -xe`.

**Comment by ssaavedra** [comment]
This is quite weird, but it seems more related to the actual evdi/displaylink code than a packaging problem.

New versions of DisplayLink and evdi have been released since, so I'll be closing this, and open a new one if you're still struggling with this.
