### ISSUE TITLE
Screen flickering when Displaylink device connected

### ISSUE THREAD

**Issue by ACiDGRiM** [displaylink-rpm/displaylink-rpm#74]
I'm having an issue in both Fedora 28/29 and Centos 7 where the screen flickers and stutters while the display link is connected. The exact behavior is the cursor will flicker when moving it, or in the case of Centos, cause an artifact to appear as a black square/a square section from another part of the overall display, or the cursor will multiple about 20 times and "re-play" the last .1 second movement for a few seconds.

I have the libva drivers for my intel iris display adapter and am running kernel 4.4 in Centos and 4.19 in Centos 29 even with this issue being a problem since F28 at least.

Functionally, the device is working well with the driver. The artifacts are just annoying.

**Comment by ssaavedra** [comment]
This is not a packaging issue. For issues related to the actual behavior of the adapter or its software, please refer to https://github.com/displaylink/evdi or the DisplayLink forums. We are unable to act on behavior since the displaylink binary is closed source.
