### ISSUE TITLE
Add proper RHEL7/Centos7 support

### ISSUE THREAD

**Issue by ssaavedra** [displaylink-rpm/displaylink-rpm#85]
It is a long standing issue (#13) that we don't properly support Centos/RHEL.

There is already some guidance in that thread about how we could fix Centos support for the next release. I'm pushing this as an issue if anybody wants to pitch in.

**Comment by thechitowncubs** [comment]
Ya, that would be nice.

**Comment by rbarakjsonar** [comment]
> It is a long standing issue (#13) that we don't properly support Centos/RHEL.
> 
> There is already some guidance in that thread about how we could fix Centos support for the next release. I'm pushing this as an issue if anybody wants to pitch in.

Could you point me to the guidance, and other resources, that would enable me to assess if I could tackle adding support for DisplayLink to CentOS 7?

**Comment by rbarakjsonar** [comment]
Could you point me to the guidance, and other resources, that would enable me to assess if I could tackle adding support for DisplayLink to CentOS 7?
