### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by ssaavedra** [displaylink-rpm/displaylink-rpm#9]
The code on this repo lacks a LICENSE, which should be an important thing to have.

I am not sure this is even copyright-able, and for what is worth, I send all my contributions to the Public Domain through CC0.

This is not about DisplayLink's license, but about the _packaging_ scripts and metadata license.

**Comment by hadess** [comment]
I would put my contributions under the same license as the Fedora spec files:
https://fedoraproject.org/wiki/Licensing:MIT#Modern_Style_with_sublicense

But we'd need to know whether @enothen thinks. The only original content left from his RPM files are the scriptlets.

**Comment by enothen** [comment]
I agree on putting my bits under the same MIT license used by the Fedora spec files

**Comment by waterfoul** [comment]
I like MIT for this too

**Comment by chuma** [comment]
I agree with putting this under the MIT license as well.
