### ISSUE TITLE
Kernel 5.1

### ISSUE THREAD

**Issue by displaylink-dkurek** [displaylink-rpm/displaylink-rpm#92]
Hi, 

just wanted to let you know there is new 
release of EVDI with support for kernels up to 5.1:
https://github.com/DisplayLink/evdi/releases/tag/v1.6.1
It should work properly with latest version of DisplayLinkManager  (5.1)
https://www.displaylink.com/downloads/ubuntu

**Comment by elguero** [comment]
@displaylink-dkurek Thank you for posting this update.  It is working well here on my Fedora 30 machine.

A pull request, #93, has been has been submitted to add evdi 1.6.1.

**Comment by ssaavedra** [comment]
Thanks for the heads-up! Are you interested in co-maintaining the project?

**Comment by displaylink-dkurek** [comment]
Not sure if this question was to me :)
You are guys doing great job on handling the repo :+1: 
it seems you don't need any help.

Anyway, support for 5.1 kernel is there, as well for 5.2.
