### ISSUE TITLE
Cannot install DisplayLink RPM on CentOS

### ISSUE THREAD

**Issue by rforberger** [displaylink-rpm/displaylink-rpm#95]
Hi,

I cannot install the centos-7-displaylink-1.6.1-1.x86_64.rpm on CentOS 7 x86_64.

The error messages i get are dependencies:

	kernel-mt > 4.7 is needed by displaylink-1.6.1-1.x86_64
	kernel-mt-devel > 4.7 is needed by displaylink-1.6.1-1.x86_64
	libstdc++.so.6(CXXABI_1.3.8)(64bit) is needed by displaylink-1.6.1-1.x86_64
	libstdc++.so.6(CXXABI_1.3.9)(64bit) is needed by displaylink-1.6.1-1.x86_64
	libstdc++.so.6(GLIBCXX_3.4.20)(64bit) is needed by displaylink-1.6.1-1.x86_64
	libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed by displaylink-1.6.1-1.x86_64
	xorg-x11-server-Xorg = 1.20.1 conflicts with displaylink-1.6.1-1.x86_64

The packages kernel-mt and kernel-mt-devel are not available.

The libstdc++ packages are installed:

```
[root@laptop02 ~]# rpm -q -a | grep libstdc++
libstdc++-4.8.5-36.el7_6.2.x86_64
libstdc++-devel-4.8.5-36.el7_6.2.x86_64
```

And I think I cannot uninstall xorg-x11-server-Xorg = 1.20.1 since it is needed for my system to work.

Any suggestions what to do here?

Best regards,
Ronny

**Comment by ssaavedra** [comment]
CentOS is not currently a supported platform. We are tracking this issue on #85 so I'll be closing this as a duplicate.
